kokoni_aspnetcore_samples/kokoni_aspnetcore_samples/Controllers/Landing/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace kokoni_aspnetcore_samples.Controllers.Landing
{
    public class LandingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

kokoni_aspnetcore_samples/kokoni_aspnetcore_samples/Controllers/Setting/SettingInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace kokoni_aspnetcore_samples.Controllers.Setting
{
    public class SettingInfoController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public SettingInfoController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            string settings = string.Empty;

            settings += _hostingEnvironment.ApplicationName + Environment.NewLine;
            settings += _hostingEnvironment.EnvironmentName + Environment.NewLine;
            settings += _hostingEnvironment.WebRootPath + Environment.NewLine;
            settings += _hostingEnvironment.ContentRootPath + Environment.NewLine;

            ViewData["setting"] = settings;

            return View();
        }
    }
}

kokoni_aspnetcore_samples/kokoni_aspnetcore_samples/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kokoni_aspnetcore_samples</title>
    <link href="~/lib/startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css" rel="stylesheet" />
    <link href="~/lib/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/lib/startbootstrap-sb-admin-2/vendor/morrisjs/morris.css" rel="stylesheet" />
    <link href="~/lib/startbootstrap-sb-admin-2/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/startbootstrap-sb-admin-2/vendor/morrisjs/morris.css" rel="stylesheet" />

    @Html.Raw(JavaScriptSnippet.FullScript)

</head>

<body>
    <!-- Navigation -->
    <div class="navbar-default sidebar" role="navigation" style="margin-top: 0px;">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="@Url.Action("Index", "Landing")"><i class="fa fa-home fa-fw"></i>kokoni-aspnetcore-samples</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial1")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial1</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial2")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial2</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial3")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial3</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial4")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial4</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial5")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial5</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tutorial6")"><i class="fa fa-bookmark-o fa-fw"></i> Tutorial6</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "SettingInfo")"><i class="fa fa-cog fa-fw"></i> サイト設定情報</a>
                </li>
            </ul>
        </div>
    </div>

    <div id="page-wrapper">
        <div class="container">
            @RenderBody()
            <hr />
        </div>
    </div>

    <footer>
        <p class="text-center">&copy; 2017 - kokoni_aspnetcore_samples</p>
    </footer>

    <script src="~/lib/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/vendor/raphael/raphael.min.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/vendor/morrisjs/morris.min.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/data/morris-data.js"></script>
    <script src="~/lib/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>